# Generated by Django 5.2.6 on 2025-09-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('forward', 'Forward'), ('midfield', 'Midfield'), ('centerback', 'Centerback'), ('fullback', 'Fullback'), ('goalkeeper', 'Goalkeeper'), ('manager', 'Manager'), ('exclusive', 'Exclusive')]),
        ),
    ]
