# Generated by Django 5.2.6 on 2025-09-16 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_product_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_views',
        ),
    ]
