# Generated by Django 5.2.6 on 2025-10-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('player_card', 'Player Card'), ('Kits', 'kits'), ('shoes', 'Shoes'), ('footballs', 'Footballs'), ('exclusive', 'Exclusive')]),
        ),
    ]
